### ISSUE TITLE
doplniť k linkom v hlavičke a v pätičke title

### ISSUE THREAD

**Issue by athelas64** [slovensko-help/korona-gov#119]
145: <a href="https://wpkorona.lamer.sk" class="idsk-header__link idsk-header__link--homepage" **title="Koronavírus a Slovensko - Domov**">
984: <a class="idsk-footer__link" href="https://www.vicepremier.gov.sk/" **title="Úrad podpredsedu vlády SR pre investície a informatizáciu"**>

**Comment by jurajk** [comment]
snad nebudem za kverulanta.

@athelas64 WCAG neodporuca pouzivat title atribut

https://www.w3.org/TR/WCAG20-TECHS/H33.html#H33-description

Because of the extensive user agent limitations in supporting access to the title attribute, authors should use caution in applying this technique. For this reason, it is preferred that the author use technique C7: Using CSS to hide a portion of the link text (CSS) or H30: Providing link text that describes the purpose of a link for anchor elements.

v id-sk je `.visually-hidden` helper classa, ktory splna odporucanu techniku C7 https://github.com/id-sk/idsk_elements/blob/master/assets/sass/elements/_helpers.scss#L22

Je pouzivane title atributu preferovane metodickym usmernenim?
Rad prejdem sablony a nahradim title atributy.

**Comment by athelas64** [comment]
Tá informácia na w3.org je trošku out of date. Tu je tabuľka s  úrovňou podpory atribútu title v prípade linkov:
![2020-04-26_08h58_03](https://user-images.githubusercontent.com/2703018/80300345-314d0300-879c-11ea-8d1b-9af2b01a012a.png)
https://www.powermapper.com/tests/screen-readers/elements/
(fajka v bielom kruhu znamená stabilnú podporu, fajkta v modrom kruhu znamená dobrú podporu).

Štandardné prvky ako alt a title majú najstabilnejšiu podporu, nie je tam žiaden problém. Ale samozrejme, CSS trik funguje, len je to také nepekné a v tomto prípade asi zbytočné.

PS: Všetok kód, čo tu postujem, je vždy najprv otestovaný a v prípade zložitejších vecí tiež konzultovaný s nevidiacim odborníkom na prístupnosť :-)

**Comment by jurajk** [comment]
Vsak ja som aj zvazoval ci to vobec rozporovat, @frkosk mi vravel ze v time je a11y expert :)

Pozrem ci to viem opravit v sablone a otvorim pull request alebo to treba vo wp admine a najdem cloveka ktory ma prisup.

**Comment by athelas64** [comment]
Akože, either way, len tým, že je to link, tak tam treba dať nejakou formou text, aby to bolo zrozumiteľné. Vďaka! 😊
